#pragma once
#include <iostream>
#include <vector>

inline std::vector<std::string> mapcolour = {
  "CLEAR",
  "PALE_GREEN ",
	"PALE_YELLOW",
	"WHITE_GRAY",
	"BRIGHT_RED",
	"PALE_PURPLE",
	"IRON_GRAY",
	"DARK_GREEN",
	"WHITE",
	"LIGHT_BLUE_GRAY",
	"DIRT_BROWN",
	"STONE_GRAY",
	"WATER_BLUE",
	"OAK_TAN",
	"OFF_WHITE",
	"ORANGE",
	"MAGENTA",
	"LIGHT_BLUE",
	"YELLOW",
	"LIME",
	"PINK",
	"GRAY",
	"LIGHT_GRAY",
	"CYAN",
	"PURPLE",
	"BLUE",
	"BROWN",
	"GREEN",
	"RED",
	"BLACK",
	"GOLD",
	"DIAMOND_BLUE",
	"LAPIS_BLUE",
	"EMERALD_GREEN",
	"SPRUCE_BROWN",
	"DARK_RED",
	"TERRACOTTA_WHITE",
	"TERRACOTTA_ORANGE",
	"TERRACOTTA_MAGENTA",
	"TERRACOTTA_LIGHT_BLUE",
	"TERRACOTTA_YELLOW",
	"TERRACOTTA_LIME",
	"TERRACOTTA_PINK",
	"TERRACOTTA_GRAY",
	"TERRACOTTA_LIGHT_GRAY",
	"TERRACOTTA_CYAN",
	"TERRACOTTA_PURPLE",
	"TERRACOTTA_BLUE",
	"TERRACOTTA_BROWN",
	"TERRACOTTA_GREEN",
	"TERRACOTTA_RED",
	"TERRACOTTA_BLACK",
	"DULL_RED",
	"DULL_PINK",
	"DARK_CRIMSON",
	"TEAL",
	"DARK_AQUA",
	"DARK_DULL_PINK",
	"BRIGHT_TEAL",
	"DEEPSLATE_GRAY",
	"RAW_IRON_PINK",
	"LICHEN_GREEN",
};

// static unless mc adds more woods
  inline std::vector<std::string> wood = {
    "oak",
    "stripped_oak",
    "spruce",
    "stripped_spruce",
    "birch",
    "stripped_birch",
    "jungle",
    "stripped_jungle",
    "acacia",
    "stripped_acacia",
    "dark_oak",
    "stripped_dark_oak",
    "mangrove",
    "stripped_mangrove",
    "cherry",
    "stripped_cherry",
    "pale_oak",
    "stripped_pale_oak",
    "bamboo",
    "stripped_bamboo",
    "crimson",
    "stripped_crimson",
    "warped",
    "stripped_warped",
  };

// static unless mc adds more colours
  inline std::vector<std::string> colour = {
    "white",
    "pink",
    "red", 
    "orange", 
    "yellow", 
    "lime", 
    "green", 
    "light blue", 
    "cyan", 
    "blue", 
    "purple", 
    "magenta", 
    "brown", 
    "light gray", 
    "gray", 
    "black",
    "pride",
    "transgender",
  };

  inline std::vector<std::string> furniture = {
    "chair",
    "stool",
    "attoman",
    "egg_chair",
    "folding_chair",
  };

  inline std::vector<std::string> mineral = {
    "copper",
    "iron",
    "gold",
    "diamond",
    "obsidian",
  };

  inline std::vector<std::string> lgbtq = {
    "pride",
    "transgender",
  };